spring:
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
#    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    hikari:
      schema: public
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS postgres
      connection-timeout: 10000

app:
  redis:
    enable: true
  integration:
    base-url: http://localhost:8082
  cache:
    cacheType: redis
    cache-names:
      - databaseEntities
      - databaseEntityByName
    caches:
      databaseEntities:
        expire: 10m
      databaseEntityByName:
        expire: 10m
